spring:
  datasource:
    url: jdbc:postgresql://db:5432/local-command-db
  flyway:
    url: jdbc:postgresql://db:5432/local-command-db
  cloud:
    zookeeper:
      enabled: true
      connect-string: zk1:3181
      client-config: /app/client.properties

axon:
  distributed:
    enabled: true
    spring-cloud:
      rest-mode-url: /member-capabilities

newrelic:
  enabled: false
  metrics:
    ingest-uri: http://wiremock:8080/metric/v1

management:
  health:
    service-registry:
      enabled: true
      interval: 60

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
