spring:
  datasource:
    url: jdbc:postgresql://db:5432/local-command-db
  flyway:
    url: jdbc:postgresql://db:5432/local-command-db
  cloud:
    zookeeper:
      connect-string: zk1:2181
      # TODO Set up TLS + auth

axon:
  distributed:
    enabled: true
    spring-cloud:
      rest-mode-url: /member-capabilities
      #fallback-to-http-get: true

newrelic:
  enabled: false
  metrics:
    ingest-uri: http://wiremock:8080/metric/v1

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
