env: prod

newrelic:
  appName: Family Recipes - Food Query - Micrometer

microservice:
  appOpts: --spring.profiles.active=prod --spring.config.additional-location=file:///app/config/application-prod.yml
  javaOpts: -Dnewrelic.environment=prod -javaagent:/usr/local/newrelic/newrelic.jar
