version: "3.7"

services:

  db:
    container_name: family-recipes-db
    image: postgres:13.8
    restart: unless-stopped
    environment:
      - POSTGRES_MULTIPLE_DATABASES="local-command-db","local-query-db"
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=sa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data/db
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - family-recipes-net

  write-model1:
    container_name: food-service-write-model1
    image: ibaiul/family-recipes:food-service-write-model-local
    pull_policy: always
    env_file: env.conf
    ports:
      - "8082:8080"
    depends_on:
      - db
      - zk1
    networks:
      - family-recipes-net
    volumes:
      - ./zookeeper/client.properties:/app/client.properties:ro
      - ./zookeeper/client-keystore.jks:/app/client-keystore.jks:ro
      - ./zookeeper/client-truststore.jks:/app/client-truststore.jks:ro

  write-model2:
    container_name: food-service-write-model2
    image: ibaiul/family-recipes:food-service-write-model-local
    pull_policy: always
    env_file: env.conf
    ports:
      - "8083:8080"
    depends_on:
      - db
      - zk1
    networks:
      - family-recipes-net
    volumes:
      - ./zookeeper/client.properties:/app/client.properties:ro
      - ./zookeeper/client-keystore.jks:/app/client-keystore.jks:ro
      - ./zookeeper/client-truststore.jks:/app/client-truststore.jks:ro

  read-model:
    container_name: food-service-read-model
    image: ibaiul/family-recipes:food-service-read-model-local
    pull_policy: always
    env_file: env.conf
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - family-recipes-net

  db-ui:
    container_name: family-recipes-db-ui
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/data/pgadmin
    depends_on:
      - db
    logging:
      driver: none
    networks:
      - family-recipes-net

  zk1:
    container_name: zk1
    hostname: zk1
    image: bitnami/zookeeper
    restart: unless-stopped
    ports:
      - "21811:2181"
      - "31811:3181"
    environment:
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=0.0.0.0:2888:3888
      - ZOO_LOG_LEVEL=ALL
      - ZOO_ENABLE_AUTH=yes
      - ZOO_TLS_CLIENT_ENABLE=true
      - ZOO_TLS_CLIENT_AUTH=need
      - ZOO_TLS_CLIENT_KEYSTORE_FILE=/bitnami/zookeeper/certs/keystore.jks
      - ZOO_TLS_CLIENT_KEYSTORE_PASSWORD=123456
      - ZOO_TLS_CLIENT_TRUSTSTORE_FILE=/bitnami/zookeeper/certs/truststore.jks
      - ZOO_TLS_CLIENT_TRUSTSTORE_PASSWORD=123456
    networks:
      - family-recipes-net
    volumes:
      - ./zookeeper/server-keystore.jks:/bitnami/zookeeper/certs/keystore.jks:ro
      - ./zookeeper/server-truststore.jks:/bitnami/zookeeper/certs/truststore.jks:ro

  zoonavigator:
    container_name: zoonavigator
    image: elkozmon/zoonavigator
    restart: unless-stopped
    ports:
      - "9000:9000"
    networks:
      - family-recipes-net

  localstack:
    image: localstack/localstack:3.2.0
    ports:
    - "4567:4566"
    environment:
      - SERVICES=s3:4566
      - HOSTNAME=localstack
      - HOSTNAME_EXTERNAL=localstack
      - DEFAULT_REGION=us-east-2
    volumes:
      - ./localstack/s3.sh:/etc/localstack/init/ready.d/init-s3.sh

volumes:
  postgres_data:
  pgadmin_data:

networks:
  family-recipes-net:
    name: family-recipes-net
    driver: bridge
