apiVersion: v1
kind: Secret
metadata:
  name: {{ include "microservice.fullname" . }}-secret
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
type: Opaque
data:
  QUERY_DB_URL_R2DBC: {{ .Values.db.query.url.r2dbc | b64enc | quote }}
  QUERY_DB_URL_JDBC: {{ .Values.db.query.url.jdbc | b64enc | quote }}
  QUERY_DB_USER: {{ .Values.db.query.user | b64enc | quote }}
  QUERY_DB_PASS: {{ .Values.db.query.pass | b64enc | quote }}
  COMMAND_DB_URL: {{ .Values.db.command.url.jdbc | b64enc | quote }}
  COMMAND_DB_USER: {{ .Values.db.command.user | b64enc | quote }}
  COMMAND_DB_PASS: {{ .Values.db.command.pass | b64enc | quote }}
  JWT_SECRET_SIGN: {{ .Values.jwt.sign | b64enc | quote }}
  JWT_SECRET_ENC: {{ .Values.jwt.enc | b64enc | quote }}
  IN_MEMORY_USER_NAME_1: {{ .Values.user1.name | b64enc | quote }}
  IN_MEMORY_USER_PASS_1: {{ .Values.user1.pass | b64enc | quote }}
  IN_MEMORY_USER_NAME_2: {{ .Values.user2.name | b64enc | quote }}
  IN_MEMORY_USER_PASS_2: {{ .Values.user2.pass | b64enc | quote }}
