server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/local-command-db
    username: sa
    password: sa
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      format_sql: false
      show_sql: false
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/local-query-db
    username: sa
    password: sa
  flyway:
    user: sa
    password: sa
    url: jdbc:postgresql://localhost:5432/local-query-db
    locations: classpath:db/migration/query/common,classpath:db/migration/query/{vendor}
    locations-command-db: classpath:db/migration/command/common,classpath:db/migration/command/{vendor}

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
  axonserver:
    enabled: false

sse:
  heartbeat:
    enabled: true
    interval: 10000

jwt:
  accessToken:
    expiration-time: 300
  refreshToken:
    expiration-time: 604800
  signature:
    secret: ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789
  encryption:
    secret: ABCDEF0123456789ABCDEF0123456789

users:
  - username: user1
    password: $2a$10$jw9IHXo.Bnm6yyZ0ggR2zut300ZYfA9b5zyhmfVI6p6YzJdZp6SqO
    roles:
      - FAMILY_MEMBER
  - username: user2
    password: $2a$10$/MevmKqa0SH9eMidXyFJAO7hEo/ZM0yNDrCzb7cZ2f5PS4uvUhojK
    roles:
      - FAMILY_MEMBER
      - ADMIN

newrelic:
  enabled: true
  app:
    name: Family Recipes - Food Query - local - Micrometer
  metrics:
    step: 60
    ingest-uri: http://localhost:18080/metric/v1
  keys:
    license: licenseKey

management:
  health:
    probes:
      enabled: true
    database:
      enabled: true
      interval: 60
    event-store:
      enabled: true
      interval: 60
    r2dbc:
      enabled: false
      interval: 60
    db:
      enabled: false
    diskSpace:
      enabled: false
    ping:
      enabled: false
  endpoint:
    info:
      enabled: true
    health:
      show-components: always
      show-details: never
  endpoints:
    web:
      exposure:
        include: health,info
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true
            percentiles: 0.95,0.99
    exclude:
      - executor
      - hikaricp
      - jvm
      - logback
      - process
      - r2dbc
      - spring
  observations:
    exclude:
      - spring.security
  info:
    env:
      enabled: true

info:
  app:
    name: Family Recipes
    description: Recipe book that also tracks what family members eat
    service: Food Service (Query side)
    version: 1.0.0

springdoc:
  webjars:
    prefix:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false