apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microservice.fullname" . }}-config
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
data:
  APP_OPTS: {{ .Values.appOpts }}
  JAVA_OPTS: {{ .Values.javaOpts }}
  NEW_RELIC_LOG: STDOUT
