apiVersion: v1
kind: Secret
metadata:
  name: {{ include "microservice.fullname" . }}-newrelic
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
type: Opaque
data:
  NEW_RELIC_LICENSE_KEY: {{ .Values.newrelic.licenseKey | b64enc | quote }}
  NEW_RELIC_METRIC_INGEST_URI: {{ .Values.newrelic.metricIngestUri | b64enc | quote }}

{{- if .Values.serviceAccount.imagePullSecrets }}
---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "microservice.fullname" . }}-pull-image
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecret | quote }}
{{- end }}
